import { NextResponse, type NextRequest } from "next/server";
import { getModule, getMeta } from "@/lib/templates/registry";
import { renderFormat, mimeFor } from "@/lib/generators";
import type { OutputFormat } from "@/lib/templates/types";
import { sanitizeFilename } from "@/lib/templates/types";

export const runtime = "nodejs"; // pdfkit + docx need Node runtime

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const mod = getModule(slug);
  const meta = getMeta(slug);
  if (!mod || !meta) {
    return NextResponse.json({ error: "Template not found or not yet implemented." }, { status: 404 });
  }

  const url = new URL(req.url);
  const format = (url.searchParams.get("format") || "pdf") as OutputFormat;
  if (!meta.formats.includes(format)) {
    return NextResponse.json(
      { error: `${format.toUpperCase()} not available for this template. Supported: ${meta.formats.join(", ").toUpperCase()}` },
      { status: 400 }
    );
  }

  let values: Record<string, string> = {};
  try {
    values = await req.json();
  } catch {
    return NextResponse.json({ error: "Body must be a JSON object of form values." }, { status: 400 });
  }

  // Validate
  if (mod.validate) {
    const errors = mod.validate(values);
    if (errors.length) {
      return NextResponse.json({ error: "Validation failed", details: errors }, { status: 422 });
    }
  }

  const sections = mod.render(values);
  const buf = await renderFormat(format, sections, {
    title: meta.name,
    author: "Lekha",
    footerText: `${meta.name} · Generated by Lekha`,
    sheetName: meta.name.slice(0, 28),
  });

  const filename = `${sanitizeFilename(meta.name)}_${Date.now()}.${format}`;
  return new NextResponse(new Uint8Array(buf), {
    status: 200,
    headers: {
      "Content-Type": mimeFor[format],
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(buf.length),
    },
  });
}
