/**
 * Test fixtures for each live template — used by the QA smoke script
 * (scripts/qa-smoke.ts) to render every format for every template with
 * realistic data, check no render throws, and file sizes are plausible.
 */

export type Fixture = Record<string, string>;

export const fixtures: Record<string, Fixture> = {
  nda: {
    nda_type: "Mutual",
    nda_date: "2026-05-01",
    nda_city: "Bengaluru",
    nda_disc_name: "Acme Pvt Ltd",
    nda_disc_rep: "Priya Sharma, Director",
    nda_disc_addr: "123 MG Road, Bengaluru 560001",
    nda_recv_name: "Vendor Co LLP",
    nda_recv_rep: "Rahul Kumar, Partner",
    nda_recv_addr: "45 Brigade Road, Bengaluru 560025",
    nda_purpose: "Evaluation of a potential SaaS licensing arrangement",
    nda_term: "3",
    nda_law: "Karnataka, India",
    nda_custom: "",
  },

  "rental-agreement": {
    ra_date: "2026-05-01",
    ra_city: "Bengaluru",
    ra_state: "Karnataka",
    ra_ll_name: "Ramesh Kumar",
    ra_ll_parent: "S/o Suresh Kumar",
    ra_ll_addr: "123 MG Road, Bengaluru 560001",
    ra_ll_pan: "AAAPR1234C",
    ra_tn_name: "Anita Sharma",
    ra_tn_parent: "D/o Rajesh Sharma",
    ra_tn_addr: "Permanent address - Pune",
    ra_tn_id: "XXXX-XXXX-4567",
    ra_prop_addr: "Flat 4B, 2 BHK, Lake View Apartments, Indiranagar, Bengaluru 560038",
    ra_prop_type: "residential",
    ra_prop_furn: "semi",
    ra_rent: "30000",
    ra_deposit: "150000",
    ra_maint: "3000",
    ra_escalation: "5",
    ra_start: "2026-06-01",
    ra_notice: "2",
    ra_custom: "",
  },

  "salary-slip": {
    ss_company: "Acme Technologies Pvt Ltd",
    ss_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    ss_pan: "AABCU9603R",
    ss_emp_name: "Priya Sharma",
    ss_emp_code: "EMP0043",
    ss_emp_dept: "Engineering",
    ss_emp_desig: "Senior Software Engineer",
    ss_emp_doj: "2024-07-01",
    ss_emp_pan: "BXQPS1234K",
    ss_emp_uan: "101234567890",
    ss_emp_bank: "XXXX4567",
    ss_period: "April 2026",
    ss_paid_days: "30",
    ss_lop_days: "0",
    ss_pay_date: "2026-05-01",
    ss_basic: "50000",
    ss_hra: "25000",
    ss_conveyance: "1600",
    ss_medical: "1250",
    ss_special: "8000",
    ss_bonus: "0",
    ss_pf: "6000",
    ss_esi: "0",
    ss_pt: "200",
    ss_tds: "8500",
    ss_other_deduct: "0",
  },

  "employment-offer": {
    eo_company: "Acme Technologies Pvt Ltd",
    eo_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    eo_signer_name: "Deepa Menon",
    eo_signer_title: "Head, Human Resources",
    eo_cand_name: "Arjun Patel",
    eo_cand_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    eo_offer_date: "2026-05-01",
    eo_desig: "Senior Software Engineer",
    eo_dept: "Engineering",
    eo_location: "Bengaluru (Hybrid)",
    eo_reporting: "Engineering Manager",
    eo_start_date: "2026-06-01",
    eo_basic: "900000",
    eo_hra: "360000",
    eo_special: "240000",
    eo_pf_employer: "108000",
    eo_gratuity: "43000",
    eo_variable: "150000",
    eo_joining_bonus: "100000",
    eo_probation: "6",
    eo_notice: "2",
    eo_offer_validity: "7",
    eo_custom: "",
  },

  affidavit: {
    af_name: "Priya Sharma",
    af_parent: "D/o Rajesh Sharma",
    af_age: "28",
    af_occupation: "Software Engineer",
    af_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    af_id_type: "aadhaar",
    af_id_number: "XXXX-XXXX-4567",
    af_type: "name_change",
    af_purpose: "For submission to Regional Passport Office",
    af_city: "Bengaluru",
    af_state: "Karnataka",
    af_date: "2026-05-01",
    af_old_name: "Priya Rajesh Sharma",
    af_new_name: "Priya Sharma",
    af_dob: "",
    af_annual_income: "",
    af_gap_from: "",
    af_gap_to: "",
    af_gap_reason: "",
    af_custom_statements: "",
  },

  "legal-notice": {
    ln_type: "demand",
    ln_date: "2026-05-01",
    ln_city: "Bengaluru",
    ln_advocate: "Vikram Singh",
    ln_bar: "KAR/1234/2018",
    ln_chamber_addr: "Suite 402, Prestige Centre, MG Road, Bengaluru 560001",
    ln_email: "vikram@lawchambers.in",
    ln_phone: "+91 98765 12345",
    ln_client_name: "ABC Constructions Pvt Ltd",
    ln_client_addr: "12 Industrial Estate, Peenya, Bengaluru 560058",
    ln_noticee_name: "XYZ Suppliers",
    ln_noticee_addr: "45 Whitefield Main Road, Bengaluru 560066",
    ln_facts: "My Client engaged your firm to supply 500 tonnes of steel rebars for a construction project, vide Purchase Order dated 1 January 2026. The agreed consideration was Rs 25,00,000, with 50% advance paid on PO and 50% on delivery. The advance of Rs 12,50,000 was transferred on 3 January 2026. Delivery was scheduled for 15 February 2026. Despite repeated follow-ups, you have failed to deliver the material or refund the advance.",
    ln_cheque_no: "",
    ln_cheque_amt: "",
    ln_cheque_bank: "",
    ln_cheque_return_date: "",
    ln_demand_amt: "1250000",
    ln_relief: "Refund the advance of Rs 12,50,000 together with interest at 12% per annum from 3 January 2026, within 15 days of receipt of this notice.",
    ln_deadline_days: "15",
  },

  "service-agreement": {
    sa_date: "2026-05-01",
    sa_city: "Bengaluru",
    sa_client_name: "Acme Technologies Pvt Ltd",
    sa_client_addr: "Plot 42, Whitefield, Bengaluru 560066",
    sa_sp_name: "Arjun Patel",
    sa_sp_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    sa_scope: "Design and develop a marketing website consisting of 5 pages (home, about, services, case studies, contact), responsive layouts for mobile and desktop, CMS integration, SEO setup, and 2 rounds of revisions. Delivery in 6 weeks.",
    sa_start: "2026-05-15",
    sa_end: "2026-06-30",
    sa_fee_type: "fixed",
    sa_fee_amount: "300000",
    sa_fee_terms: "50% on signing, 25% on design approval, 25% on go-live. Net 15 days.",
    sa_expense: "",
    sa_ip: "client",
    sa_nda: "yes",
    sa_term_notice: "15",
    sa_law: "Karnataka, India",
    sa_custom: "",
  },

  will: {
    w_name: "Ramesh Kumar",
    w_parent: "S/o late Suresh Kumar",
    w_age: "68",
    w_occupation: "Retired",
    w_religion: "Hindu",
    w_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    w_date: "2026-05-01",
    w_city: "Bengaluru",
    w_exec_name: "Anita Sharma",
    w_exec_rel: "Daughter",
    w_exec_addr: "25 Hosur Road, Bengaluru 560029",
    w_alt_exec_name: "Rahul Kumar, Son",
    w_bequests: "Flat 4B, Lake View Apartments - to my son Rahul Kumar\nFixed deposit of Rs 20,00,000 in HDFC Bank - to my daughter Anita Sharma\nGold jewellery - to my wife Sunita Kumar\nMaruti Swift car KA-01-AB-1234 - to my son Rahul Kumar",
    w_residuary: "my wife Sunita Kumar",
    w_wit1_name: "Vikram Singh",
    w_wit1_addr: "45 MG Road, Bengaluru",
    w_wit2_name: "Dr. Meera Reddy",
    w_wit2_addr: "12 Indiranagar, Bengaluru",
  },

  "power-of-attorney": {
    poa_type: "special",
    poa_date: "2026-05-01",
    poa_city: "Bengaluru",
    poa_state: "Karnataka",
    poa_p_name: "Ramesh Kumar",
    poa_p_parent: "S/o late Suresh Kumar",
    poa_p_age: "68",
    poa_p_occupation: "Retired",
    poa_p_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    poa_a_name: "Rahul Kumar",
    poa_a_parent: "S/o Ramesh Kumar",
    poa_a_age: "38",
    poa_a_rel: "Son",
    poa_a_addr: "25 Hosur Road, Bengaluru 560029",
    poa_property_desc: "Flat No. 4B, 2 BHK, Lake View Apartments, Indiranagar, Bengaluru 560038",
    poa_acts: "To sign and present the sale deed for registration before the Sub-Registrar\nTo collect sale consideration and issue receipts\nTo represent me in all matters related to the sale\nTo sign and execute ancillary documents",
    poa_duration: "specific_purpose",
    poa_end_date: "",
    poa_sub_power: "no",
  },

  "partnership-deed": {
    pd_firm_name: "M/s Acme Traders",
    pd_business: "Trading in electronic goods and related accessories",
    pd_place: "45 MG Road, Bengaluru 560001",
    pd_date: "2026-05-01",
    pd_city: "Bengaluru",
    pd_start: "2026-06-01",
    pd_p1_name: "Ramesh Kumar",
    pd_p1_addr: "123 MG Road, Bengaluru 560001",
    pd_p1_capital: "500000",
    pd_p1_share: "50",
    pd_p2_name: "Suresh Reddy",
    pd_p2_addr: "45 Brigade Road, Bengaluru 560025",
    pd_p2_capital: "500000",
    pd_p2_share: "50",
    pd_p3_name: "",
    pd_p3_addr: "",
    pd_p3_capital: "",
    pd_p3_share: "",
    pd_p4_name: "",
    pd_p4_addr: "",
    pd_p4_capital: "",
    pd_p4_share: "",
    pd_interest_capital: "6",
    pd_remuneration: "Each working partner shall draw a monthly remuneration of Rs 50,000 subject to the limits under section 40(b).",
    pd_fy_end: "31_mar",
    pd_bank: "HDFC Bank, Indiranagar Branch",
    pd_custom: "",
  },

  "appointment-letter": {
    al_company: "Acme Technologies Pvt Ltd",
    al_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    al_signer_name: "Deepa Menon",
    al_signer_title: "Head, Human Resources",
    al_letter_date: "2026-05-01",
    al_emp_name: "Arjun Patel",
    al_emp_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    al_emp_id: "EMP0127",
    al_join_date: "2026-05-15",
    al_desig: "Senior Software Engineer",
    al_dept: "Engineering",
    al_location: "Bengaluru (Hybrid)",
    al_reporting: "Engineering Manager",
    al_basic: "600000",
    al_hra: "240000",
    al_conveyance: "19200",
    al_medical: "15000",
    al_special: "160000",
    al_pf_er: "72000",
    al_gratuity: "28800",
    al_insurance: "36000",
    al_variable: "150000",
    al_probation: "6",
    al_notice: "2",
    al_retire_age: "58",
    al_leaves: "24",
  },

  "experience-letter": {
    el_company: "Acme Technologies Pvt Ltd",
    el_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    el_letter_date: "2026-05-01",
    el_signer: "Deepa Menon",
    el_signer_title: "Head, Human Resources",
    el_emp_name: "Arjun Patel",
    el_emp_id: "EMP0127",
    el_from: "2024-07-01",
    el_to: "2026-04-30",
    el_last_desig: "Senior Software Engineer",
    el_dept: "Engineering",
    el_responsibilities: "Led backend development for the payments module; mentored 3 junior engineers; owned deployment pipeline.",
  },

  "termination-letter": {
    tl_company: "Acme Technologies Pvt Ltd",
    tl_letter_date: "2026-05-01",
    tl_signer: "Deepa Menon",
    tl_signer_title: "Head, Human Resources",
    tl_emp_name: "Arjun Patel",
    tl_emp_id: "EMP0127",
    tl_emp_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    tl_desig: "Senior Software Engineer",
    tl_reason: "performance",
    tl_reason_details: "As discussed in the performance reviews dated 1 February 2026 and 15 March 2026, and in the Performance Improvement Plan that concluded on 30 April 2026, your performance has not met the required standards.",
    tl_effective: "2026-05-31",
    tl_notice_type: "pay_in_lieu",
    tl_notice_days: "60",
    tl_fnf_amount: "240000",
    tl_handover: "Return laptop (Asset ID L-0127), access cards, and company documents to HR. Complete handover of ongoing projects to Ananya Shah by 31 May 2026.",
  },

  "relieving-letter": {
    rl_company: "Acme Technologies Pvt Ltd",
    rl_letter_date: "2026-05-01",
    rl_signer: "Deepa Menon",
    rl_signer_title: "Head, Human Resources",
    rl_emp_name: "Arjun Patel",
    rl_emp_id: "EMP0127",
    rl_desig: "Senior Software Engineer",
    rl_dept: "Engineering",
    rl_resig_date: "2026-03-01",
    rl_last_working_day: "2026-04-30",
    rl_join_date: "2024-07-01",
  },

  "gift-deed": {
    gd_date: "2026-05-01",
    gd_city: "Bengaluru",
    gd_state: "Karnataka",
    gd_donor_name: "Ramesh Kumar",
    gd_donor_parent: "S/o late Suresh Kumar",
    gd_donor_age: "68",
    gd_donor_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    gd_donor_pan: "AAAPR1234C",
    gd_donee_name: "Rahul Kumar",
    gd_donee_parent: "S/o Ramesh Kumar",
    gd_donee_age: "38",
    gd_donee_addr: "25 Hosur Road, Bengaluru 560029",
    gd_donee_relation: "Son",
    gd_prop_type: "residential",
    gd_prop_desc: "Flat No. 4B, 2 BHK, 1250 sq ft built-up, Lake View Apartments, Indiranagar, Bengaluru 560038; bounded by - North: Flat 4A; South: Corridor; East: Main Road; West: Parking",
    gd_prop_value: "15000000",
    gd_acquisition: "Purchased vide Sale Deed dated 12 March 2005, registered at SRO Bengaluru East, Reg No. IND-2005-1234",
  },

  "lease-agreement": {
    la_date: "2026-05-01",
    la_city: "Bengaluru",
    la_state: "Karnataka",
    la_term_years: "5",
    la_start: "2026-06-01",
    la_lessor_name: "Ramesh Kumar",
    la_lessor_addr: "Flat 4B, Lake View Apartments, Bengaluru 560038",
    la_lessor_pan: "AAAPR1234C",
    la_lessee_name: "Acme Technologies Pvt Ltd",
    la_lessee_addr: "Plot 42, Whitefield, Bengaluru 560066",
    la_lessee_pan: "AABCA1234M",
    la_prop_use: "commercial",
    la_prop_desc: "Ground floor commercial space, 2500 sq ft carpet area, Unit A-1, Acme Commercial Plaza, 100 Feet Road, Indiranagar, Bengaluru 560038",
    la_area: "2500",
    la_rent: "200000",
    la_escalation_pct: "5",
    la_deposit: "1200000",
    la_lock_in_months: "24",
    la_maint: "25000",
    la_notice_months: "3",
    la_custom: "",
  },

  "data-governance-policy": {
    dg_org_name: "Acme Technologies Pvt Ltd",
    dg_effective_date: "2026-01-01",
    dg_review_date: "2027-01-01",
    dg_dpo_name: "Vikram Patel",
    dg_dpo_email: "privacy@acme.test",
    dg_approver_name: "Board of Directors",
    dg_scope: "customer_employee",
    dg_processes_children: "yes",
    dg_intl_transfer: "yes",
    dg_retention_months: "36",
    dg_breach_hours: "72",
  },

  // ── Auto-generated fixtures (QA backfill) — derived from each module's field schema;
  // every format render-tested with no throws. ──
  "affidavit-general": {
    "aff_name": "Priya Sharma",
    "aff_age": "32",
    "aff_father_spouse": "Ramesh Sharma",
    "aff_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "aff_state": "Andhra Pradesh",
    "aff_city": "Sample Value",
    "aff_id_type": "aadhar",
    "aff_id_no": "XXXX XXXX 1234 (Aadhaar)",
    "aff_purpose": "name_change",
    "aff_old_name": "Priya Sharma",
    "aff_new_name": "Priya Rahul Sharma",
    "aff_dob_old": "2026-05-01",
    "aff_dob_new": "2026-05-01",
    "aff_annual_income": "600000",
    "aff_lost_doc": "Degree Certificate in B.Tech from XYZ University, Year 2015",
    "aff_custom_content": "I, the deponent, hereby solemnly declare that...",
    "aff_place_of_swearing": "Bengaluru",
  },
  "board-resolution": {
    "br_company_name": "Acme Technologies Private Limited",
    "br_cin": "U72900KA2021PTC123456",
    "br_registered_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "br_meeting_date": "2026-05-01",
    "br_meeting_place": "Bengaluru, Karnataka",
    "br_chairman": "Arjun Sharma",
    "br_company_secretary": "CS Meera Nair",
    "br_director1": "Arjun Sharma",
    "br_director1_din": "07654321",
    "br_director2": "Meena Kapoor",
    "br_director2_din": "07654322",
    "br_director3": "Sample Value",
    "br_director3_din": "Sample Value",
    "br_resolution_type": "bank_account",
    "br_bank_name": "HDFC Bank Limited",
    "br_bank_branch": "Koramangala, Bengaluru",
    "br_loan_amount": "10000000",
    "br_authorized_person": "Arjun Sharma",
    "br_authorized_designation": "Managing Director",
    "br_contract_party": "AWS India",
    "br_contract_value": "500000",
    "br_resolution_text": "Describe the specific resolution to be passed\u2026",
  },
  "board-resolution-allotment": {
    "bra_co_name": "Acme Technologies Private Limited",
    "bra_cin": "U72900KA2024PTC123456",
    "bra_co_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "bra_meeting_date": "2026-05-01",
    "bra_meeting_city": "Sample Value",
    "bra_state": "Andhra Pradesh",
    "bra_chair": "Sample Value",
    "bra_directors_present": "Priya Sharma, Rahul Verma",
    "bra_instrument": "equity",
    "bra_allotment_basis": "private_placement",
    "bra_num_shares": "10000",
    "bra_face_value": "10",
    "bra_issue_price": "1000",
    "bra_total_consideration": "10000000",
    "bra_ppo_date": "2026-05-01",
    "bra_allottee_type": "domestic_investor",
    "bra_allottees_list": "Sequoia Capital India Investments | AABCS1234C | 5000\nAccel Partners India | AABCA5678D | 5000",
    "bra_fdi": "no",
    "bra_fdi_sector": "IT / SaaS \u2014 100% automatic route",
    "bra_pre_paid_up": "1000000",
    "bra_pre_shares": "100000",
    "bra_authorised_capital": "5000000",
  },
  "board-resolution-director": {
    "brd_co_name": "Acme Technologies Private Limited",
    "brd_cin": "U72900KA2024PTC123456",
    "brd_co_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "brd_meeting_date": "2026-05-01",
    "brd_meeting_city": "Sample Value",
    "brd_state": "Andhra Pradesh",
    "brd_chair": "Sample Value",
    "brd_directors_present": "Priya Sharma, Rahul Verma",
    "brd_resolution_type": "appoint",
    "brd_dir_name": "Arjun Mehta",
    "brd_dir_din": "01234567",
    "brd_dir_pan": "AABCM1234D",
    "brd_dir_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "brd_dir_email": "test@example.com",
    "brd_dir_mobile": "9876543210",
    "brd_dir_nationality": "indian",
    "brd_appt_date": "2026-05-01",
    "brd_resign_date_letter": "2026-05-01",
    "brd_id_tenure_years": "5",
    "brd_remuneration": "nil",
    "brd_sitting_fee": "50000",
    "brd_monthly_salary": "200000",
  },
  "code-of-conduct": {
    "coc_company_name": "Acme Technologies Pvt Ltd",
    "coc_effective_date": "2026-05-01",
    "coc_ceo_name": "Arjun Sharma",
    "coc_hr_name": "Pooja Nair",
    "coc_hr_designation": "Head \u2014 Human Resources",
    "coc_reporting_email": "test@example.com",
    "coc_anti_bribery": "yes",
    "coc_social_media": "yes",
    "coc_gift_limit": "1000",
    "coc_insider_trading": "no",
  },
  "consultancy-agreement": {
    "ca_client_name": "Acme Technologies Private Limited",
    "ca_client_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ca_client_signatory": "Priya Sharma, CEO",
    "ca_consultant_name": "Rajesh Kumar / Kumar Advisory LLP",
    "ca_consultant_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ca_consultant_pan": "AABCK1234D",
    "ca_consultant_type": "individual",
    "ca_consultant_gstin": "29AABCK1234C1ZX",
    "ca_scope": "Strategic advisory on market expansion into Southeast Asia; competitive intelligence; quarterly board presentations; introduction to investor network.",
    "ca_start_date": "2026-05-01",
    "ca_term": "12months",
    "ca_time_commitment": "2\u20133 days per month / up to 8 hours per week",
    "ca_fee_type": "retainer",
    "ca_retainer_amount": "100000",
    "ca_hourly_rate": "5000",
    "ca_success_fee": "0.25% ESOP on Series A close / 2% of deal value on M&A transaction close",
    "ca_gst_applicable": "yes",
    "ca_payment_day": "5th of each month / 30 days from invoice",
    "ca_non_solicit_months": "12",
    "ca_conf_years": "3",
    "ca_jurisdiction_city": "Mumbai",
    "ca_jurisdiction_state": "Andhra Pradesh",
  },
  "copyright-assignment": {
    "ca_assignor_name": "Vikram Nair (or Acme Creative Studios Pvt Ltd)",
    "ca_assignor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ca_assignor_type": "individual",
    "ca_assignor_rep": "Vikram Nair, Director",
    "ca_assignee_name": "TechStartup Private Limited",
    "ca_assignee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ca_assignee_rep": "Priya Sharma, CEO",
    "ca_work_type": "software",
    "ca_work_title": "A mobile application for GST reconciliation named 'GST-Buddy', version 1.0 and all subsequent versions, including all source code, documentation, and UI/UX designs.",
    "ca_creation_date": "2026-05-01",
    "ca_first_pub_date": "2026-05-01",
    "ca_reg_no": "L-123456/2024",
    "ca_future_works": "yes",
    "ca_rights_assigned": "all",
    "ca_territory_scope": "worldwide",
    "ca_consideration": "500000",
    "ca_consideration_type": "lump_sum",
    "ca_royalty_rate": "10",
    "ca_moral_rights": "waived",
  },
  "distribution-agreement": {
    "da_sup_name": "Acme Electronics Private Limited",
    "da_sup_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "da_sup_gstin": "29AABCA1234C1ZX",
    "da_sup_signatory": "Priya Sharma, Director \u2014 Sales",
    "da_dist_name": "Northern Distribution LLP",
    "da_dist_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "da_dist_gstin": "07AABCN5678D1ZY",
    "da_dist_signatory": "Rahul Gupta, Managing Partner",
    "da_products": "All SKUs under the 'AcmePro' range of consumer electronics \u2014 see Product List (Schedule A)",
    "da_territory": "States of Punjab, Haryana, Delhi NCT, and Himachal Pradesh",
    "da_exclusivity": "exclusive",
    "da_agreement_date": "2026-05-01",
    "da_term_years": "2",
    "da_minimum_purchase": "5000000",
    "da_pricing_basis": "trade_price",
    "da_distributor_margin": "30",
    "da_payment_terms": "30",
    "da_credit_limit": "2000000",
    "da_rpm_clause": "suggested_only",
    "da_stock_return": "yes",
    "da_warranty_period": "12",
    "da_jurisdiction_city": "Delhi",
    "da_jurisdiction_state": "Andhra Pradesh",
  },
  "dpdp-privacy-notice": {
    "dp_org_name": "Acme Technologies Pvt Ltd",
    "dp_org_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "dp_website": "https://www.acmetechnologies.in",
    "dp_effective_date": "2026-05-01",
    "dp_dpo_name": "Priya Sharma",
    "dp_dpo_email": "test@example.com",
    "dp_grievance_resolution_days": "30",
    "dp_audience": "customers",
    "dp_collects_sensitive": "no",
    "dp_children_data": "no",
    "dp_cross_border": "no",
    "dp_cross_border_countries": "United States, Singapore",
    "dp_retention_period": "As long as necessary for the stated purpose or as required by law",
  },
  "employee-nda": {
    "enda_company_name": "Acme Technologies Pvt Ltd",
    "enda_company_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "enda_signatory_name": "Ananya Krishnan",
    "enda_signatory_designation": "Head \u2014 Human Resources",
    "enda_deed_date": "2026-05-01",
    "enda_emp_name": "Arjun Mehta",
    "enda_emp_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "enda_designation": "Senior Software Engineer",
    "enda_department": "Engineering",
    "enda_doj": "2026-05-01",
    "enda_nda_term": "3",
    "enda_non_solicit": "yes",
    "enda_non_solicit_period": "12",
    "enda_ip_assignment": "yes",
    "enda_jurisdiction": "India",
    "enda_city": "Bengaluru",
  },
  "fnf-settlement": {
    "fnf_company_name": "Acme Technologies Pvt Ltd",
    "fnf_company_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "fnf_hr_name": "Priya Sharma",
    "fnf_hr_designation": "Head \u2014 Human Resources",
    "fnf_letter_date": "2026-05-01",
    "fnf_emp_name": "Vikram Mehta",
    "fnf_emp_id": "EMP-2020-112",
    "fnf_designation": "Senior Engineer",
    "fnf_department": "Engineering",
    "fnf_doj": "2026-05-01",
    "fnf_dol": "2026-05-01",
    "fnf_separation_type": "resignation",
    "fnf_last_monthly_gross": "80000",
    "fnf_basic_salary": "32000",
    "fnf_days_worked_last_month": "15",
    "fnf_days_in_last_month": "31",
    "fnf_notice_period_days": "60",
    "fnf_notice_served_days": "60",
    "fnf_leaves_pending": "12",
    "fnf_reimbursements_pending": "5000",
    "fnf_performance_bonus": "0",
    "fnf_advances_recovery": "0",
    "fnf_asset_recovery": "0",
    "fnf_other_deductions": "0",
    "fnf_other_deductions_desc": "Mobile bill recovery",
    "fnf_pf_applicable": "yes",
    "fnf_gratuity_applicable": "auto",
  },
  "franchise-agreement": {
    "fa_franchisor_name": "Tasty Bites Foods Private Limited",
    "fa_franchisor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "fa_brand_name": "Tasty Bites",
    "fa_franchisor_gstin": "07AABCT1234C1ZX",
    "fa_franchisor_signatory": "Ankit Gupta, Director",
    "fa_franchisee_name": "Sharma Enterprises / Mohan Sharma",
    "fa_franchisee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "fa_franchisee_pan": "AABCS5678D",
    "fa_franchisee_gstin": "29AABCS5678D1ZY",
    "fa_franchisee_signatory": "Mohan Sharma, Proprietor",
    "fa_territory": "Indiranagar, Bengaluru (within a 2 km radius of the outlet at 12th Main Road) / HSR Layout ward, Bengaluru",
    "fa_outlet_addr": "Shop No. 5, 12th Main Road, Indiranagar, Bengaluru \u2013 560 038",
    "fa_exclusivity": "exclusive",
    "fa_agreement_date": "2026-05-01",
    "fa_term_years": "5",
    "fa_renewal_years": "5",
    "fa_franchise_fee": "500000",
    "fa_royalty_type": "percent_revenue",
    "fa_royalty_percent": "6",
    "fa_royalty_fixed": "25000",
    "fa_marketing_fund": "2% of monthly gross revenue",
    "fa_security_deposit": "200000",
    "fa_royalty_payment_day": "10th of the following month",
    "fa_operations_manual": "Tasty Bites Operations Manual v3.0 (2024)",
    "fa_quality_audit": "quarterly",
    "fa_training_days": "21 days at franchisor's training centre",
    "fa_jurisdiction_city": "Bengaluru",
    "fa_jurisdiction_state": "Andhra Pradesh",
  },
  "freelancer-agreement": {
    "fl_client_name": "Acme Marketing Private Limited",
    "fl_client_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "fl_client_signatory": "Meera Patel, Marketing Head",
    "fl_freelancer_name": "Arjun Mehta",
    "fl_freelancer_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "fl_freelancer_pan": "AABCM1234D",
    "fl_freelancer_gstin": "29AABCM1234D1ZX",
    "fl_skill_type": "design",
    "fl_project_name": "Brand Identity Redesign \u2014 Q1 2025",
    "fl_scope": "1. Brand logo (5 concepts, 2 revision rounds)\n2. Brand style guide (colour palette, typography, usage guidelines)\n3. Social media profile templates (Facebook, Instagram, LinkedIn)\n4. Business card and letterhead design\n\nAll in AI/PSD source files + PDF exports.",
    "fl_start_date": "2026-05-01",
    "fl_end_date": "2026-05-01",
    "fl_revisions": "2 rounds of revisions per deliverable",
    "fl_payment_type": "fixed",
    "fl_total_fee": "75000",
    "fl_advance": "25000",
    "fl_milestone_desc": "50% on signing\n25% on logo approval\n25% on final delivery of all files",
    "fl_gst_applicable": "no",
    "fl_ip_ownership": "client_on_payment",
    "fl_conf_years": "2",
    "fl_portfolio_rights": "yes",
    "fl_jurisdiction_city": "Bengaluru",
  },
  "gst-invoice": {
    "inv_sup_name": "Acme Technologies Private Limited",
    "inv_sup_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "inv_sup_gstin": "29AABCA1234C1ZX",
    "inv_sup_state": "Andhra Pradesh",
    "inv_sup_email": "test@example.com",
    "inv_sup_phone": "9876543210",
    "inv_number": "INV-2024-0042",
    "inv_date": "2026-05-01",
    "inv_due_date": "30 days / Due by DD-MM-YYYY",
    "inv_supply_type": "services",
    "inv_transaction_type": "b2b",
    "inv_reverse_charge": "no",
    "inv_e_invoicing": "no",
    "inv_irn": "a1b2c3d4...64-character hash",
    "inv_ack_no": "232412345678901",
    "inv_ack_date": "2026-05-01",
    "inv_buy_name": "Beta Solutions Private Limited / Rahul Verma",
    "inv_buy_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "inv_buy_gstin": "27AABCB9876D1ZY",
    "inv_buy_state": "Andhra Pradesh",
    "inv_buy_pos": "Andhra Pradesh",
    "inv_buy_email": "test@example.com",
    "inv_items_raw": "Cloud Hosting Services | 998315 | 1 | Month | 50000 | 0\nSetup & Onboarding | 998311 | 1 | Service | 10000 | 0\nSupport Retainer | 998313 | 1 | Month | 15000 | 5000",
    "inv_gst_rate": "18",
    "inv_notes": "Bank: HDFC Bank | A/C: 1234567890 | IFSC: HDFC0001234 | UPI: billing@acme",
  },
  "hr-appointment-letter": {
    "al_co_name": "Acme Technologies Private Limited",
    "al_co_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "al_co_gstin": "Sample Value",
    "al_hr_name": "Sneha Patel, VP \u2014 People",
    "al_letter_date": "2026-05-01",
    "al_emp_name": "Rahul Verma",
    "al_emp_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "al_designation": "Senior Software Engineer",
    "al_department": "Engineering",
    "al_reporting_to": "Priya Sharma, CTO",
    "al_joining_date": "2026-05-01",
    "al_work_location": "Bengaluru (Koramangala)",
    "al_employment_type": "full_time_permanent",
    "al_contract_end_date": "2026-05-01",
    "al_ctc_annual": "1200000",
    "al_basic_pct": "40",
    "al_hra_pct": "50",
    "al_variable_pct": "0",
    "al_pf_applicable": "yes",
    "al_esic_applicable": "no",
    "al_gratuity_note": "yes",
    "al_probation_months": "6",
    "al_notice_period_probation": "1_week",
    "al_notice_period_confirmed": "2_months",
    "al_working_hours": "9_5",
    "al_leave_annual": "18",
    "al_leave_sick": "12",
    "al_wfh": "hybrid",
    "al_non_compete_months": "0",
  },
  "hr-nda-employee": {
    "nda_emp_co_name": "Acme Technologies Private Limited",
    "nda_emp_co_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "nda_emp_co_cin": "U72900MH2020PTC345678",
    "nda_emp_signatory": "Priya Sharma, Director",
    "nda_ee_name": "Rahul Verma",
    "nda_ee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "nda_ee_type": "employee",
    "nda_ee_designation": "Senior Software Engineer",
    "nda_ee_department": "Engineering",
    "nda_agreement_date": "2026-05-01",
    "nda_scope_type": "broad",
    "nda_scope_custom": "Specify the categories of confidential information...",
    "nda_includes_personal_data": "yes",
    "nda_ip_assignment": "yes",
    "nda_post_term": "3",
    "nda_non_solicit": "yes",
    "nda_jurisdiction_city": "Bengaluru",
    "nda_jurisdiction_state": "Andhra Pradesh",
  },
  "hr-relieving-letter": {
    "rl_co_name": "Acme Technologies Private Limited",
    "rl_co_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "rl_hr_name": "Sneha Patel, VP \u2014 People",
    "rl_letter_date": "2026-05-01",
    "rl_emp_name": "Rahul Verma",
    "rl_emp_id": "EMP-1234",
    "rl_designation": "Senior Software Engineer",
    "rl_department": "Engineering",
    "rl_date_of_joining": "2026-05-01",
    "rl_last_working_day": "2026-05-01",
    "rl_separation_type": "resignation",
    "rl_conduct": "good",
    "rl_clearance": "yes",
    "rl_fnf_note": "F&F payment will be processed within 45 days as per company policy.",
    "rl_recommend": "yes",
  },
  "increment-letter": {
    "il_company_name": "Acme Technologies Pvt Ltd",
    "il_company_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "il_hr_name": "Ananya Krishnan",
    "il_hr_designation": "Head \u2014 Human Resources",
    "il_emp_name": "Vikram Joshi",
    "il_emp_id": "EMP-2019-045",
    "il_designation": "Senior Software Engineer",
    "il_department": "Engineering",
    "il_letter_date": "2026-05-01",
    "il_effective_date": "2026-05-01",
    "il_old_ctc": "1200000",
    "il_new_ctc": "1500000",
    "il_increment_type": "performance",
    "il_new_designation": "Sample Value",
    "il_performance_rating": "Exceeds Expectations",
    "il_basic_salary": "50000",
    "il_hra": "20000",
    "il_special_allowance": "30000",
    "il_additional_message": "Sample descriptive text provided for QA smoke testing of this field.",
  },
  "infosec-policy": {
    "isp_org_name": "Acme Technologies Pvt Ltd",
    "isp_effective_date": "2026-05-01",
    "isp_review_date": "2026-05-01",
    "isp_ciso_name": "Vikram Patel",
    "isp_ciso_email": "test@example.com",
    "isp_ceo_name": "Sample Value",
    "isp_framework": "iso27001",
    "isp_cloud_scope": "yes",
    "isp_bcdr_rto": "4",
    "isp_bcdr_rpo": "1",
    "isp_incident_notify_hours": "4",
    "isp_password_length": "12",
    "isp_mfa_required": "yes",
  },
  "internship-letter": {
    "int_company_name": "Acme Technologies Pvt Ltd",
    "int_company_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "int_hr_name": "Ananya Krishnan",
    "int_hr_designation": "Head \u2014 Human Resources",
    "int_letter_date": "2026-05-01",
    "int_name": "Aditya Verma",
    "int_college": "IIT Bombay",
    "int_course": "B.Tech Computer Science (Final Year)",
    "int_email": "test@example.com",
    "int_role": "Product Engineering Intern",
    "int_department": "Engineering \u2014 Platform",
    "int_start_date": "2026-05-01",
    "int_end_date": "2026-05-01",
    "int_stipend": "15000",
    "int_work_mode": "in_office",
    "int_office_addr": "Bengaluru, Karnataka",
    "int_project": "Work on building the data pipeline for the analytics platform using Python and Apache Spark.",
    "int_mentor": "Rahul Nair, Senior Engineer",
    "int_working_hours": "9:30 AM \u2013 6:30 PM, Monday to Friday",
    "int_certificate": "yes",
    "int_ppo": "based_on_performance",
  },
  "joint-venture-agreement": {
    "jv_p1_name": "Alpha Industries Private Limited",
    "jv_p1_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "jv_p1_country": "India",
    "jv_p1_signatory": "Suresh Gupta, Managing Director",
    "jv_p2_name": "Beta Tech GmbH",
    "jv_p2_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "jv_p2_country": "Germany",
    "jv_p2_signatory": "Hans M\u00fcller, CEO",
    "jv_structure": "jv_company",
    "jv_entity_name": "AlphaBeta Technologies Private Limited",
    "jv_purpose": "Development and commercialisation of AI-based quality inspection systems for the Indian manufacturing sector.",
    "jv_agreement_date": "2026-05-01",
    "jv_term": "perpetual",
    "jv_state": "Andhra Pradesh",
    "jv_p1_equity": "51",
    "jv_p2_equity": "49",
    "jv_p1_contribution": "\u20b92,00,00,000 cash + land & building valued at \u20b93,00,00,000",
    "jv_p2_contribution": "Technology licence, know-how, and \u20b91,50,00,000 cash",
    "jv_foreign_partner": "no",
    "jv_fdi_sector": "Manufacturing (100% FDI, automatic route) / Defence (74% automatic, above requires GoI approval)",
    "jv_p1_board_seats": "3",
    "jv_p2_board_seats": "2",
    "jv_reserved_matters": "yes",
    "jv_exit_mechanism": "put_call",
    "jv_non_compete_years": "2",
    "jv_jurisdiction_city": "Mumbai",
  },
  "leave-license": {
    "ll_licensor_name": "Rajesh Mehta",
    "ll_licensor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ll_licensor_pan": "AABCM1234D",
    "ll_licensor_aadhar": "XXXX",
    "ll_licensee_name": "Sunita Patil",
    "ll_licensee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ll_licensee_pan": "AABCP5678E",
    "ll_licensee_company": "Sample Value",
    "ll_premises_addr": "Flat No. 201, 2nd Floor, Sunrise CHS, Sector 17, Vashi, Navi Mumbai \u2013 400 703",
    "ll_premises_type": "residential_flat",
    "ll_carpet_area": "750 sq ft",
    "ll_city": "Navi Mumbai",
    "ll_survey_no": "CTS No. 456/A",
    "ll_start_date": "2026-05-01",
    "ll_term_months": "11",
    "ll_license_fee": "25000",
    "ll_deposit": "75000",
    "ll_advance_months": "0",
    "ll_due_day": "5",
    "ll_escalation": "5_pct",
    "ll_notice_period": "1",
    "ll_purpose": "residential",
    "ll_maintenance": "2000",
    "ll_parking": "1",
    "ll_witness1": "Sample Value",
    "ll_witness2": "Sample Value",
    "ll_additional_terms": "Sample descriptive text provided for QA smoke testing of this field.",
  },
  "leave-policy": {
    "lp_company_name": "Acme Technologies Pvt Ltd",
    "lp_effective_date": "2026-05-01",
    "lp_leave_year": "jan_dec",
    "lp_hr_name": "Pooja Nair",
    "lp_hr_designation": "Head \u2014 Human Resources",
    "lp_cl_days": "12",
    "lp_sl_days": "12",
    "lp_el_days": "15",
    "lp_el_carryforward": "30",
    "lp_maternity_days": "182",
    "lp_paternity_days": "5",
    "lp_bereavement_days": "3",
    "lp_optional_holidays": "2",
    "lp_wfh_clause": "no",
    "lp_lop_clause": "yes",
  },
  "legal-notice-general": {
    "ln_client_name": "Priya Sharma / Acme Technologies Pvt Ltd",
    "ln_client_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ln_client_type": "individual",
    "ln_advocate_name": "Adv. Arjun Mehta",
    "ln_advocate_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ln_advocate_enrol": "KAR/1234/2010",
    "ln_send_method": "rpad",
    "ln_noticee_name": "Rahul Verma / XYZ Builders Pvt Ltd",
    "ln_noticee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ln_noticee_type": "individual",
    "ln_noticee_email": "test@example.com",
    "ln_dispute_type": "money_recovery",
    "ln_background": "On [date], my client entered into a [contract type] with you for [purpose]. Despite fulfilling all obligations, you have failed to [specific failure]. Specifically:\n1. On [date], [event 1].\n2. On [date], [event 2].\n3. Despite [demands / reminders], you have failed to respond / comply.",
    "ln_amount_claimed": "500000",
    "ln_interest_rate": "18",
    "ln_period_of_default": "Since [date] to date",
    "ln_documents_relied": "Invoice No. INV-2024-001 dated [date]; Agreement dated [date]; Email correspondence dated [dates]",
    "ln_demand": "Pay the outstanding amount of \u20b95,00,000 along with interest at 18% p.a. from [date] to date of payment.\n\nOR\n\nVacate the premises at [address] and hand over vacant possession forthwith.",
    "ln_response_days": "15",
    "ln_consequences": "civil_suit",
    "ln_without_prejudice": "no",
  },
  "mortgage-deed": {
    "md_mortgagor_name": "Suresh Kumar Patel",
    "md_mortgagor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "md_mortgagor_pan": "AABCP1234D",
    "md_mortgagor_aadhar": "XXXX",
    "md_mortgagee_name": "State Bank of India",
    "md_mortgagee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "md_mortgagee_type": "bank",
    "md_property_desc": "All that piece and parcel of residential flat No. 301, 3rd Floor, Shanti Heights, Sector 12, Dwarka, New Delhi \u2013 110 078, measuring 1,400 sq ft\u2026",
    "md_state": "Delhi",
    "md_city": "New Delhi",
    "md_area_sqft": "1400",
    "md_survey_no": "Plot No. 12, Sector 12",
    "md_title_document": "Sale Deed dated 10/03/2020, Doc No. 789/2020",
    "md_mortgage_type": "simple",
    "md_loan_amount": "5000000",
    "md_deed_date": "2026-05-01",
    "md_interest_rate": "8.5",
    "md_interest_type": "reducing",
    "md_repayment_months": "240",
    "md_emi_day": "1",
    "md_repayment_start_date": "2026-05-01",
    "md_prepayment_penalty": "nil",
  },
  "noc-letter": {
    "noc_issuer_name": "Acme Technologies Private Limited",
    "noc_issuer_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "noc_issuer_designation": "HR Manager / CEO / Landlord / Branch Manager",
    "noc_ref_no": "HR/NOC/2024-25/001",
    "noc_date": "2026-05-01",
    "noc_beneficiary_name": "Rahul Verma",
    "noc_beneficiary_id": "Employee ID: EMP-123 / Tenant / Borrower / Student",
    "noc_beneficiary_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "noc_type": "employment_visa",
    "noc_purpose": "To apply for a long-term business visa to the United States of America to attend client meetings and conferences. / To pursue a part-time MBA programme at IIM Bangalore. / No dues outstanding on Home Loan Account No. HL-123456.",
    "noc_address_to": "The Embassy of the United States of America, New Delhi / Admissions Office, IIM Bangalore",
    "noc_validity": "3_months",
    "noc_employment_since": "2026-05-01",
    "noc_designation_role": "Software Engineer",
    "noc_loan_account": "HL-123456789",
    "noc_property_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "noc_conditions": "no",
    "noc_conditions_text": "This NOC is valid only for the specific purpose stated herein. The employee's primary employment obligations shall continue to take precedence.",
  },
  "patent-licence": {
    "pl_licensor_name": "InnovateTech Research Private Limited",
    "pl_licensor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "pl_licensor_rep": "Dr. Arjun Mehta, CEO",
    "pl_licensor_type": "company",
    "pl_licensee_name": "Acme Manufacturing Private Limited",
    "pl_licensee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "pl_licensee_rep": "Priya Sharma, Director",
    "pl_patent_title": "A Method and System for Real-time GST Reconciliation Using Machine Learning",
    "pl_patent_no": "IN 345678",
    "pl_app_no": "201841012345",
    "pl_filing_date": "2026-05-01",
    "pl_grant_date": "2026-05-01",
    "pl_expiry_date": "2026-05-01",
    "pl_related_patents": "PCT/IN2018/012345; US 11,234,567; EP 3,123,456",
    "pl_licence_type": "non_exclusive",
    "pl_field_of_use": "Manufacture and sale of GST reconciliation software for SMEs in India. Excludes large enterprise / banking sector applications.",
    "pl_territory": "india_only",
    "pl_start_date": "2026-05-01",
    "pl_term_type": "fixed",
    "pl_end_date": "2026-05-01",
    "pl_sublicence": "no",
    "pl_royalty_type": "running_royalty",
    "pl_royalty_rate": "5",
    "pl_minimum_royalty": "500000",
    "pl_upfront_fee": "1000000",
    "pl_payment_frequency": "quarterly",
    "pl_cross_border": "no",
    "pl_improvements_ownership": "licensor",
  },
  "posh-complaint-procedure": {
    "posh_org_name": "Acme Technologies Private Limited",
    "posh_org_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "posh_org_type": "private_co",
    "posh_effective_date": "2026-05-01",
    "posh_policy_version": "v1.0 / 2024",
    "posh_presiding_officer": "Priya Sharma, VP \u2014 People",
    "posh_member_2": "Anita Rao, Senior Manager \u2014 Engineering",
    "posh_member_3": "Deepa Mehta, Deputy Manager \u2014 Finance",
    "posh_external_member": "Kavita Krishnan \u2014 Advocate, Bengaluru Bar Association",
    "posh_icc_email": "test@example.com",
    "posh_icc_term": "3",
    "posh_workplace_desc": "All offices, remote/work-from-home, client sites, off-site events, and any other location where Company work is performed",
    "posh_employee_count": "10_50",
    "posh_nodal_officer": "Sunita Patel, HR Manager \u2014 posh-hr@company.com",
    "posh_grievance_email": "test@example.com",
    "posh_includes_third_party": "yes",
    "posh_remote_work": "yes",
    "posh_gender_scope": "all_genders",
  },
  "posh-policy": {
    "posh_org_name": "Acme Technologies Pvt Ltd",
    "posh_org_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "posh_effective_date": "2026-05-01",
    "posh_emp_count": "150",
    "posh_ic_presiding_officer": "Nisha Mehta",
    "posh_ic_presiding_designation": "Senior Manager \u2014 HR",
    "posh_ic_member1": "Kavita Rao",
    "posh_ic_member1_desig": "Team Lead \u2014 Engineering",
    "posh_ic_member2": "Ravi Shankar",
    "posh_ic_member2_desig": "Manager \u2014 Legal",
    "posh_ic_external_member": "Dr. Priya Desai",
    "posh_ic_external_org": "Sakhi Women's Collective",
    "posh_nodal_officer": "Anand Verma",
    "posh_nodal_email": "test@example.com",
  },
  "probation-confirmation": {
    "pc_company_name": "Acme Technologies Pvt Ltd",
    "pc_company_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "pc_hr_name": "Sunita Reddy",
    "pc_hr_designation": "Head \u2014 Human Resources",
    "pc_letter_date": "2026-05-01",
    "pc_emp_name": "Rohan Kapoor",
    "pc_emp_id": "EMP-2025-220",
    "pc_designation": "Software Engineer",
    "pc_department": "Engineering",
    "pc_doj": "2026-05-01",
    "pc_probation_end_date": "2026-05-01",
    "pc_probation_months": "6",
    "pc_salary_revision": "no",
    "pc_old_ctc": "600000",
    "pc_new_ctc": "700000",
    "pc_new_designation": "Sample Value",
    "pc_performance_note": "Your performance during the probation period has been commendable and you have demonstrated excellent technical skills\u2026",
    "pc_benefits_note": "Group Medical Insurance, PF contributions, and Annual Increment cycle",
  },
  "professional-tax-challan": {
    "pt_emp_name": "Acme Technologies Private Limited",
    "pt_emp_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "pt_enroll_no": "27970123456789",
    "pt_regn_no": "27970123456789P",
    "pt_state": "Andhra Pradesh",
    "pt_signatory": "Priya Sharma, HR Manager",
    "pt_month": "april",
    "pt_year": "2024-25",
    "pt_payment_date": "2026-05-01",
    "pt_challan_no": "CIN generated after bank payment",
    "pt_bank_name": "State Bank of India, Fort Branch, Mumbai",
    "pt_employees_raw": "Rahul Verma | 85000 | 200\nPriya Sharma | 55000 | 200\nAmit Kumar | 18000 | 150\nSunita Patel | 10000 | 100",
    "pt_include_slab_table": "yes",
  },
  "relinquishment-deed": {
    "rd_releasor_name": "Suresh Sharma",
    "rd_releasor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "rd_releasor_pan": "AABCS1234C",
    "rd_releasor_aadhar": "1234 5678 9012",
    "rd_releasor_share": "1/3 (one-third) / 33.33%",
    "rd_how_acquired": "inheritance",
    "rd_releasee_name": "Priya Sharma",
    "rd_releasee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "rd_releasee_pan": "AABCP5678D",
    "rd_releasee_aadhar": "9876 5432 1098",
    "rd_relationship": "sibling",
    "rd_property_desc": "All that piece and parcel of the residential flat bearing Door No. 302, 3rd Floor, Prestige Towers, Survey No. 12/1, Koramangala, Bengaluru \u2013 560 034, measuring approximately 1,200 sq ft super built-up area, comprised in Sy. No. 12/1, bounded on the East by..., bounded on the West by...",
    "rd_state": "Andhra Pradesh",
    "rd_market_value": "8000000",
    "rd_doc_list": "Sale deed dated [date] registered as Doc No. [no.] in SRO [name]; Probate / succession certificate dated [date]",
    "rd_consideration": "nil",
    "rd_consideration_amount": "1000000",
    "rd_deed_date": "2026-05-01",
    "rd_other_coowners": "no",
    "rd_other_coowners_names": "Mahesh Sharma, Kavita Sharma",
  },
  "remote-work-policy": {
    "rwp_company_name": "Acme Technologies Pvt Ltd",
    "rwp_effective_date": "2026-05-01",
    "rwp_hr_name": "Pooja Nair",
    "rwp_hr_designation": "Head \u2014 Human Resources",
    "rwp_it_contact": "test@example.com",
    "rwp_model": "hybrid",
    "rwp_office_days": "2",
    "rwp_core_hours_start": "10:00 AM",
    "rwp_core_hours_end": "5:00 PM",
    "rwp_max_consecutive_wfh": "5",
    "rwp_equipment_provided": "yes",
    "rwp_internet_stipend": "1000",
    "rwp_international_remote": "no",
  },
  "rent-agreement": {
    "ra_landlord_name": "Suresh Kumar",
    "ra_landlord_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ra_landlord_pan": "AABCS1234C",
    "ra_landlord_aadhar": "XXXX",
    "ra_tenant_name": "Priya Sharma",
    "ra_tenant_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ra_tenant_pan": "AABCT5678D",
    "ra_tenant_company": "Acme Technologies Pvt Ltd (for employee accommodation)",
    "ra_co_tenant": "Sample Value",
    "ra_property_addr": "Flat No. 302, 3rd Floor, Prestige Sunrise Tower, 15th Cross, Koramangala 4th Block, Bengaluru \u2013 560 034",
    "ra_property_type": "residential_flat",
    "ra_carpet_area": "950 sq ft",
    "ra_state": "Andhra Pradesh",
    "ra_city": "Sample Value",
    "ra_furnishing": "semi_furnished",
    "ra_fixtures_list": "AC (2 units), refrigerator, washing machine, modular kitchen with chimney, water purifier",
    "ra_start_date": "2026-05-01",
    "ra_term_months": "11",
    "ra_monthly_rent": "30000",
    "ra_maintenance": "3000",
    "ra_maintenance_who": "tenant",
    "ra_security_deposit": "90000",
    "ra_advance_months": "0",
    "ra_rent_due_day": "5",
    "ra_rent_escalation": "5_pct",
    "ra_lock_in": "3_months",
    "ra_notice_period": "1",
    "ra_pets": "no",
    "ra_subletting": "no",
    "ra_tds": "no",
    "ra_parking": "yes",
    "ra_parking_spaces": "1",
  },
  "sale-agreement": {
    "sa_vendor_name": "Ramesh Kumar Sharma",
    "sa_vendor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "sa_vendor_pan": "AABCS1234D",
    "sa_vendor_aadhar": "XXXX",
    "sa_purchaser_name": "Priya Nair",
    "sa_purchaser_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "sa_purchaser_pan": "AABCP5678E",
    "sa_purchaser_company": "Sample Value",
    "sa_property_desc": "All that piece and parcel of residential flat bearing No. 4B, 4th Floor, Prestige Towers, Survey No. 45/2A, Koramangala, Bengaluru \u2013 560 095, measuring 1,200 sq ft carpet area\u2026",
    "sa_state": "Karnataka",
    "sa_city": "Bengaluru",
    "sa_area_sqft": "1200",
    "sa_survey_no": "Survey No. 45/2A",
    "sa_title_document": "Sale Deed dated 12/06/2018 registered as Doc No. 456/2018",
    "sa_total_consideration": "7500000",
    "sa_token_amount": "500000",
    "sa_token_date": "2026-05-01",
    "sa_second_instalment": "2000000",
    "sa_second_instalment_date": "2026-05-01",
    "sa_balance_amount": "5000000",
    "sa_registration_deadline": "2026-05-01",
    "sa_possession_date": "2026-05-01",
    "sa_possession_condition": "vacant",
    "sa_encumbrance": "free",
    "sa_mortgage_bank": "HDFC Bank",
    "sa_mortgage_amount": "3500000",
  },
  "sale-deed": {
    "sd_seller_name": "Suresh Kumar Sharma",
    "sd_seller_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "sd_seller_pan": "AABCS1234C",
    "sd_seller_aadhar": "1234 5678 9012",
    "sd_seller_2_name": "Sunita Sharma (wife)",
    "sd_seller_nri": "no",
    "sd_buyer_name": "Priya Sharma",
    "sd_buyer_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "sd_buyer_pan": "AABCP5678D",
    "sd_buyer_aadhar": "9876 5432 1098",
    "sd_buyer_2_name": "Rahul Sharma (husband)",
    "sd_buyer_nri": "no",
    "sd_property_type": "residential_flat",
    "sd_property_addr": "Flat No. 302, 3rd Floor, Prestige Sunrise Tower, Survey No. 15/2, Koramangala 4th Block, Bengaluru \u2013 560 034",
    "sd_survey_no": "Survey No. 15/2, Koramangala Village",
    "sd_extent": "950 sq ft super built-up area / 2,400 sq ft / 30\u00d740 sq ft plot",
    "sd_state": "Andhra Pradesh",
    "sd_city": "Sample Value",
    "sd_sro": "SRO Koramangala, Bengaluru",
    "sd_rera": "no",
    "sd_rera_no": "PRM/KA/RERA/1251/309/PR/171017/001234",
    "sd_sale_consideration": "8000000",
    "sd_guideline_value": "7500000",
    "sd_payment_mode": "bank_transfer",
    "sd_loan_amount": "5000000",
    "sd_loan_bank": "HDFC Bank Limited",
    "sd_advance_paid": "500000",
    "sd_advance_date": "2026-05-01",
    "sd_balance_payable": "7500000",
    "sd_title_doc": "Sale deed dated [date], Doc No. [no.], Book I, CD No. [no.], registered at SRO [name], by [prior seller] to [seller].",
    "sd_encumbrance": "Nil encumbrances as per EC for last 30 years. / Existing home loan of \u20b9X with [Bank] being discharged simultaneously.",
    "sd_occupation_certificate": "yes",
  },
  "share-certificate": {
    "sc_co_name": "Acme Technologies Private Limited",
    "sc_cin": "U72900KA2024PTC123456",
    "sc_co_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "sc_incorp_date": "2026-05-01",
    "sc_authorised_capital": "5000000",
    "sc_paid_up_capital": "1000000",
    "sc_cert_no": "001",
    "sc_folio_no": "F-001",
    "sc_issue_date": "2026-05-01",
    "sc_share_class": "equity",
    "sc_face_value": "10",
    "sc_num_shares": "1000",
    "sc_from_folio": "1",
    "sc_to_folio": "1000",
    "sc_allotment_basis": "allotment",
    "sc_allotment_date": "2026-05-01",
    "sc_member_name": "Priya Sharma",
    "sc_member_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "sc_member_pan": "AABCS1234C",
    "sc_joint_holder_1": "Rahul Sharma",
    "sc_joint_holder_2": "Sample Value",
    "sc_holding_mode": "jointly",
    "sc_nominee": "Sunita Sharma",
    "sc_dir1_name": "Priya Sharma",
    "sc_dir1_din": "01234567",
    "sc_dir2_name": "Rahul Verma",
    "sc_dir2_din": "07654321",
    "sc_cs_name": "Anita Iyer (ACS 12345)",
  },
  "startup-ndia": {
    "ndia_entity_name": "Acme Technologies Private Limited",
    "ndia_entity_type": "pvt_ltd",
    "ndia_cin": "U72900KA2024PTC123456",
    "ndia_incorp_date": "2026-05-01",
    "ndia_reg_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "ndia_state": "Andhra Pradesh",
    "ndia_pan": "AABCT1234C",
    "ndia_gstin": "29AABCT1234C1ZB",
    "ndia_website": "https://www.acmetech.in",
    "ndia_promoters": "Priya Sharma (DIN: 01234567), Rahul Verma (DIN: 07654321)",
    "ndia_auth_signatory": "Priya Sharma, CEO & Director",
    "ndia_auth_din": "01234567",
    "ndia_board_date": "2026-05-01",
    "ndia_sector": "technology",
    "ndia_turnover_crore": "10",
    "ndia_prior_recognition": "no",
    "ndia_existing_recognition": "no",
    "ndia_existing_cert_no": "DIPP12345",
    "ndia_innovation_type": "product",
    "ndia_innovation_desc": "We have developed an AI-powered SaaS platform that automates GST reconciliation for SMEs using machine learning. Unlike existing products, our platform integrates directly with Tally, Zoho Books, and GSTN APIs to auto-match purchase records and flag mismatches in real time, reducing reconciliation time by 90%. This product is novel, scalable, and addresses a significant unmet need in the Indian SME market.",
    "ndia_scalability": "The platform is currently used by 150 SMEs and is capable of scaling to 10,000+ customers without proportionate increase in costs. We plan to hire 20 additional engineers and sales personnel over the next 12 months.",
    "ndia_current_employees": "12",
    "ndia_ip_status": "none",
    "ndia_ip_details": "Patent App. No. 202141012345",
    "ndia_80iac": "yes",
    "ndia_self_cert_labour": "yes",
    "ndia_self_cert_env": "no",
    "ndia_govt_tenders": "no",
    "ndia_ipr_fee": "yes",
  },
  "tds-certificate-form16": {
    "f16_emp_name": "Acme Technologies Private Limited",
    "f16_emp_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "f16_emp_tan": "MUMB12345A",
    "f16_emp_pan": "AABCA1234B",
    "f16_emp_cin": "U72900MH2020PTC345678",
    "f16_ee_name": "Rahul Verma",
    "f16_ee_pan": "AABCV5678D",
    "f16_ee_designation": "Senior Software Engineer",
    "f16_ee_empid": "EMP-1234",
    "f16_ee_doj": "2026-05-01",
    "f16_ee_dol": "2026-05-01",
    "f16_fy": "2024-25",
    "f16_ay": "2025-26",
    "f16_basic": "720000",
    "f16_hra_received": "288000",
    "f16_hra_exempt": "180000",
    "f16_lta_received": "25000",
    "f16_lta_exempt": "25000",
    "f16_special_allowance": "180000",
    "f16_other_allowances": "0",
    "f16_bonus": "60000",
    "f16_perquisites": "0",
    "f16_gross_salary": "1320000",
    "f16_regime": "new",
    "f16_std_deduction": "75000",
    "f16_prof_tax": "2400",
    "f16_80c": "150000",
    "f16_80d": "25000",
    "f16_80ccd_1b": "50000",
    "f16_80g": "0",
    "f16_other_deductions": "80E: \u20b90; 80EEA: \u20b90",
    "f16_other_deductions_amount": "0",
    "f16_home_loan_interest": "200000",
    "f16_tds_q1": "22500",
    "f16_tds_q2": "22500",
    "f16_tds_q3": "22500",
    "f16_tds_q4": "22500",
    "f16_cert_no": "ABC1234567",
    "f16_issue_date": "2026-05-01",
    "f16_signatory": "Priya Sharma, HR Manager",
  },
  "trademark-assignment": {
    "tma_assignor_name": "Acme Brands Private Limited",
    "tma_assignor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "tma_assignor_type": "company",
    "tma_assignor_rep": "Priya Sharma, CEO",
    "tma_assignee_name": "NewCo Technologies Private Limited",
    "tma_assignee_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "tma_assignee_type": "company",
    "tma_assignee_rep": "Rahul Verma, Director",
    "tma_tm_name": "ACMETECH",
    "tma_tm_logo": "Stylised letter A in blue and orange",
    "tma_tm_status": "registered",
    "tma_reg_no": "5012345",
    "tma_classes": "Class 9, Class 42",
    "tma_goods_services": "Software as a service (SaaS); computer software; IT consultancy services",
    "tma_reg_date": "2026-05-01",
    "tma_renewal_date": "2026-05-01",
    "tma_assignment_type": "complete_with_goodwill",
    "tma_partial_scope": "Class 9 goods only (excluding Class 42 services)",
    "tma_consideration": "500000",
    "tma_consideration_type": "lump_sum",
    "tma_effective_date": "2026-05-01",
    "tma_pending_proceedings": "no",
    "tma_proceeding_details": "Opposition No. TMO/OP/2023/123456 pending before Trademarks Registry, Mumbai",
  },
  "vendor-dpa": {
    "dpa_fiduciary_name": "Acme Technologies Pvt Ltd",
    "dpa_fiduciary_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "dpa_fiduciary_signatory": "Rajesh Mehta",
    "dpa_fiduciary_designation": "Chief Privacy Officer",
    "dpa_processor_name": "CloudServices Pvt Ltd",
    "dpa_processor_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "dpa_processor_signatory": "Priya Kapoor",
    "dpa_processor_designation": "Chief Executive Officer",
    "dpa_agreement_date": "2026-05-01",
    "dpa_processing_description": "Processing of customer contact data, usage analytics, and support tickets for the purpose of providing cloud CRM services.",
    "dpa_data_categories": "Name, email address, phone number, usage logs, support communication records",
    "dpa_data_subjects": "Customers, leads, support users",
    "dpa_processing_location": "India (Mumbai), Singapore",
    "dpa_term_months": "24",
    "dpa_breach_notify_hours": "72",
    "dpa_gdpr_applicable": "no",
    "dpa_jurisdiction": "India",
    "dpa_city": "Bengaluru",
  },
  "warning-letter": {
    "wl_company_name": "Acme Technologies Pvt Ltd",
    "wl_hr_name": "Deepa Verma",
    "wl_hr_designation": "Head \u2014 Human Resources",
    "wl_emp_name": "Rohit Sharma",
    "wl_emp_id": "EMP-2021-078",
    "wl_designation": "Sales Executive",
    "wl_department": "Sales",
    "wl_letter_date": "2026-05-01",
    "wl_warning_type": "first_warning",
    "wl_violation_category": "misconduct",
    "wl_incident_date": "2026-05-01",
    "wl_incident_description": "Describe the specific incident, behaviour, or policy violation in detail. Include dates, witnesses, and any prior verbal warnings given.",
    "wl_prior_warnings": "Verbal warning on 15/03/2026",
    "wl_reply_deadline_days": "3",
    "wl_consequences": "termination",
  },
  "will-testament": {
    "wt_testator_name": "Ramesh Kumar Sharma",
    "wt_testator_age": "55",
    "wt_testator_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "wt_testator_religion": "hindu",
    "wt_state": "Andhra Pradesh",
    "wt_will_date": "2026-05-01",
    "wt_place": "Bengaluru",
    "wt_executor_1_name": "Priya Sharma (daughter)",
    "wt_executor_1_rel": "Daughter",
    "wt_executor_1_addr": "Sample descriptive text provided for QA smoke testing of this field.",
    "wt_executor_2_name": "Rahul Sharma (son)",
    "wt_executor_2_rel": "Son",
    "wt_spouse_name": "Sunita Sharma",
    "wt_children": "Priya Sharma (30), Rahul Sharma (27), Ananya Sharma (minor, age 12)",
    "wt_minor_children": "no",
    "wt_guardian_name": "Sunita Sharma (mother) / Priya Sharma (elder sister)",
    "wt_immovable_bequests": "1. Flat No. 302, Prestige Tower, Bengaluru \u2014 to my daughter Priya Sharma absolutely.\n2. Ancestral house at [Village/Town] \u2014 to my son Rahul Sharma absolutely.\n3. Plot No. 45, [Layout], Bengaluru \u2014 to be sold and proceeds divided equally between Priya Sharma and Rahul Sharma.",
    "wt_bank_bequests": "1. SBI Savings Account No. XXXXXXXXXX, SBI Koramangala Branch \u2014 to my wife Sunita Sharma.\n2. HDFC FD maturing in [year] \u2014 to be divided equally between Priya Sharma and Rahul Sharma.\n3. PPF Account with SBI \u2014 to my wife Sunita Sharma.",
    "wt_investments_bequests": "1. All shares held in demat account with Zerodha (DP ID: XXXXXXXXXX) \u2014 to my daughter Priya Sharma.\n2. Mutual fund units in HDFC AMC folio [no.] \u2014 to my son Rahul Sharma.",
    "wt_jewellery_bequests": "All gold jewellery in my possession / locker at SBI Koramangala \u2014 to my wife Sunita Sharma. Specific gold chain (50g) and ring (10g) \u2014 to my daughter Priya Sharma.",
    "wt_residuary": "All remaining assets, movable and immovable, not specifically bequeathed herein, to be divided equally between my children Priya Sharma and Rahul Sharma.",
    "wt_debts": "executor",
    "wt_funeral": "As per Hindu customs and rites.",
    "wt_prior_wills": "yes",
  },
};
