/**
 * Test fixtures for each live template — used by the QA smoke script
 * (scripts/qa-smoke.ts) to render every format for every template with
 * realistic data, check no render throws, and file sizes are plausible.
 */

export type Fixture = Record<string, string>;

export const fixtures: Record<string, Fixture> = {
  nda: {
    nda_type: "Mutual",
    nda_date: "2026-05-01",
    nda_city: "Bengaluru",
    nda_disc_name: "Acme Pvt Ltd",
    nda_disc_rep: "Priya Sharma, Director",
    nda_disc_addr: "123 MG Road, Bengaluru 560001",
    nda_recv_name: "Vendor Co LLP",
    nda_recv_rep: "Rahul Kumar, Partner",
    nda_recv_addr: "45 Brigade Road, Bengaluru 560025",
    nda_purpose: "Evaluation of a potential SaaS licensing arrangement",
    nda_term: "3",
    nda_law: "Karnataka, India",
    nda_custom: "",
  },

  "rental-agreement": {
    ra_date: "2026-05-01",
    ra_city: "Bengaluru",
    ra_state: "Karnataka",
    ra_ll_name: "Ramesh Kumar",
    ra_ll_parent: "S/o Suresh Kumar",
    ra_ll_addr: "123 MG Road, Bengaluru 560001",
    ra_ll_pan: "AAAPR1234C",
    ra_tn_name: "Anita Sharma",
    ra_tn_parent: "D/o Rajesh Sharma",
    ra_tn_addr: "Permanent address - Pune",
    ra_tn_id: "XXXX-XXXX-4567",
    ra_prop_addr: "Flat 4B, 2 BHK, Lake View Apartments, Indiranagar, Bengaluru 560038",
    ra_prop_type: "residential",
    ra_prop_furn: "semi",
    ra_rent: "30000",
    ra_deposit: "150000",
    ra_maint: "3000",
    ra_escalation: "5",
    ra_start: "2026-06-01",
    ra_notice: "2",
    ra_custom: "",
  },

  "salary-slip": {
    ss_company: "Acme Technologies Pvt Ltd",
    ss_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    ss_pan: "AABCU9603R",
    ss_emp_name: "Priya Sharma",
    ss_emp_code: "EMP0043",
    ss_emp_dept: "Engineering",
    ss_emp_desig: "Senior Software Engineer",
    ss_emp_doj: "2024-07-01",
    ss_emp_pan: "BXQPS1234K",
    ss_emp_uan: "101234567890",
    ss_emp_bank: "XXXX4567",
    ss_period: "April 2026",
    ss_paid_days: "30",
    ss_lop_days: "0",
    ss_pay_date: "2026-05-01",
    ss_basic: "50000",
    ss_hra: "25000",
    ss_conveyance: "1600",
    ss_medical: "1250",
    ss_special: "8000",
    ss_bonus: "0",
    ss_pf: "6000",
    ss_esi: "0",
    ss_pt: "200",
    ss_tds: "8500",
    ss_other_deduct: "0",
  },

  "employment-offer": {
    eo_company: "Acme Technologies Pvt Ltd",
    eo_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    eo_signer_name: "Deepa Menon",
    eo_signer_title: "Head, Human Resources",
    eo_cand_name: "Arjun Patel",
    eo_cand_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    eo_offer_date: "2026-05-01",
    eo_desig: "Senior Software Engineer",
    eo_dept: "Engineering",
    eo_location: "Bengaluru (Hybrid)",
    eo_reporting: "Engineering Manager",
    eo_start_date: "2026-06-01",
    eo_basic: "900000",
    eo_hra: "360000",
    eo_special: "240000",
    eo_pf_employer: "108000",
    eo_gratuity: "43000",
    eo_variable: "150000",
    eo_joining_bonus: "100000",
    eo_probation: "6",
    eo_notice: "2",
    eo_offer_validity: "7",
    eo_custom: "",
  },

  affidavit: {
    af_name: "Priya Sharma",
    af_parent: "D/o Rajesh Sharma",
    af_age: "28",
    af_occupation: "Software Engineer",
    af_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    af_id_type: "aadhaar",
    af_id_number: "XXXX-XXXX-4567",
    af_type: "name_change",
    af_purpose: "For submission to Regional Passport Office",
    af_city: "Bengaluru",
    af_state: "Karnataka",
    af_date: "2026-05-01",
    af_old_name: "Priya Rajesh Sharma",
    af_new_name: "Priya Sharma",
    af_dob: "",
    af_annual_income: "",
    af_gap_from: "",
    af_gap_to: "",
    af_gap_reason: "",
    af_custom_statements: "",
  },

  "legal-notice": {
    ln_type: "demand",
    ln_date: "2026-05-01",
    ln_city: "Bengaluru",
    ln_advocate: "Vikram Singh",
    ln_bar: "KAR/1234/2018",
    ln_chamber_addr: "Suite 402, Prestige Centre, MG Road, Bengaluru 560001",
    ln_email: "vikram@lawchambers.in",
    ln_phone: "+91 98765 12345",
    ln_client_name: "ABC Constructions Pvt Ltd",
    ln_client_addr: "12 Industrial Estate, Peenya, Bengaluru 560058",
    ln_noticee_name: "XYZ Suppliers",
    ln_noticee_addr: "45 Whitefield Main Road, Bengaluru 560066",
    ln_facts: "My Client engaged your firm to supply 500 tonnes of steel rebars for a construction project, vide Purchase Order dated 1 January 2026. The agreed consideration was Rs 25,00,000, with 50% advance paid on PO and 50% on delivery. The advance of Rs 12,50,000 was transferred on 3 January 2026. Delivery was scheduled for 15 February 2026. Despite repeated follow-ups, you have failed to deliver the material or refund the advance.",
    ln_cheque_no: "",
    ln_cheque_amt: "",
    ln_cheque_bank: "",
    ln_cheque_return_date: "",
    ln_demand_amt: "1250000",
    ln_relief: "Refund the advance of Rs 12,50,000 together with interest at 12% per annum from 3 January 2026, within 15 days of receipt of this notice.",
    ln_deadline_days: "15",
  },

  "service-agreement": {
    sa_date: "2026-05-01",
    sa_city: "Bengaluru",
    sa_client_name: "Acme Technologies Pvt Ltd",
    sa_client_addr: "Plot 42, Whitefield, Bengaluru 560066",
    sa_sp_name: "Arjun Patel",
    sa_sp_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    sa_scope: "Design and develop a marketing website consisting of 5 pages (home, about, services, case studies, contact), responsive layouts for mobile and desktop, CMS integration, SEO setup, and 2 rounds of revisions. Delivery in 6 weeks.",
    sa_start: "2026-05-15",
    sa_end: "2026-06-30",
    sa_fee_type: "fixed",
    sa_fee_amount: "300000",
    sa_fee_terms: "50% on signing, 25% on design approval, 25% on go-live. Net 15 days.",
    sa_expense: "",
    sa_ip: "client",
    sa_nda: "yes",
    sa_term_notice: "15",
    sa_law: "Karnataka, India",
    sa_custom: "",
  },

  will: {
    w_name: "Ramesh Kumar",
    w_parent: "S/o late Suresh Kumar",
    w_age: "68",
    w_occupation: "Retired",
    w_religion: "Hindu",
    w_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    w_date: "2026-05-01",
    w_city: "Bengaluru",
    w_exec_name: "Anita Sharma",
    w_exec_rel: "Daughter",
    w_exec_addr: "25 Hosur Road, Bengaluru 560029",
    w_alt_exec_name: "Rahul Kumar, Son",
    w_bequests: "Flat 4B, Lake View Apartments - to my son Rahul Kumar\nFixed deposit of Rs 20,00,000 in HDFC Bank - to my daughter Anita Sharma\nGold jewellery - to my wife Sunita Kumar\nMaruti Swift car KA-01-AB-1234 - to my son Rahul Kumar",
    w_residuary: "my wife Sunita Kumar",
    w_wit1_name: "Vikram Singh",
    w_wit1_addr: "45 MG Road, Bengaluru",
    w_wit2_name: "Dr. Meera Reddy",
    w_wit2_addr: "12 Indiranagar, Bengaluru",
  },

  "power-of-attorney": {
    poa_type: "special",
    poa_date: "2026-05-01",
    poa_city: "Bengaluru",
    poa_state: "Karnataka",
    poa_p_name: "Ramesh Kumar",
    poa_p_parent: "S/o late Suresh Kumar",
    poa_p_age: "68",
    poa_p_occupation: "Retired",
    poa_p_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    poa_a_name: "Rahul Kumar",
    poa_a_parent: "S/o Ramesh Kumar",
    poa_a_age: "38",
    poa_a_rel: "Son",
    poa_a_addr: "25 Hosur Road, Bengaluru 560029",
    poa_property_desc: "Flat No. 4B, 2 BHK, Lake View Apartments, Indiranagar, Bengaluru 560038",
    poa_acts: "To sign and present the sale deed for registration before the Sub-Registrar\nTo collect sale consideration and issue receipts\nTo represent me in all matters related to the sale\nTo sign and execute ancillary documents",
    poa_duration: "specific_purpose",
    poa_end_date: "",
    poa_sub_power: "no",
  },

  "partnership-deed": {
    pd_firm_name: "M/s Acme Traders",
    pd_business: "Trading in electronic goods and related accessories",
    pd_place: "45 MG Road, Bengaluru 560001",
    pd_date: "2026-05-01",
    pd_city: "Bengaluru",
    pd_start: "2026-06-01",
    pd_p1_name: "Ramesh Kumar",
    pd_p1_addr: "123 MG Road, Bengaluru 560001",
    pd_p1_capital: "500000",
    pd_p1_share: "50",
    pd_p2_name: "Suresh Reddy",
    pd_p2_addr: "45 Brigade Road, Bengaluru 560025",
    pd_p2_capital: "500000",
    pd_p2_share: "50",
    pd_p3_name: "",
    pd_p3_addr: "",
    pd_p3_capital: "",
    pd_p3_share: "",
    pd_p4_name: "",
    pd_p4_addr: "",
    pd_p4_capital: "",
    pd_p4_share: "",
    pd_interest_capital: "6",
    pd_remuneration: "Each working partner shall draw a monthly remuneration of Rs 50,000 subject to the limits under section 40(b).",
    pd_fy_end: "31_mar",
    pd_bank: "HDFC Bank, Indiranagar Branch",
    pd_custom: "",
  },

  "appointment-letter": {
    al_company: "Acme Technologies Pvt Ltd",
    al_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    al_signer_name: "Deepa Menon",
    al_signer_title: "Head, Human Resources",
    al_letter_date: "2026-05-01",
    al_emp_name: "Arjun Patel",
    al_emp_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    al_emp_id: "EMP0127",
    al_join_date: "2026-05-15",
    al_desig: "Senior Software Engineer",
    al_dept: "Engineering",
    al_location: "Bengaluru (Hybrid)",
    al_reporting: "Engineering Manager",
    al_basic: "600000",
    al_hra: "240000",
    al_conveyance: "19200",
    al_medical: "15000",
    al_special: "160000",
    al_pf_er: "72000",
    al_gratuity: "28800",
    al_insurance: "36000",
    al_variable: "150000",
    al_probation: "6",
    al_notice: "2",
    al_retire_age: "58",
    al_leaves: "24",
  },

  "experience-letter": {
    el_company: "Acme Technologies Pvt Ltd",
    el_company_addr: "Plot 42, Whitefield, Bengaluru 560066",
    el_letter_date: "2026-05-01",
    el_signer: "Deepa Menon",
    el_signer_title: "Head, Human Resources",
    el_emp_name: "Arjun Patel",
    el_emp_id: "EMP0127",
    el_from: "2024-07-01",
    el_to: "2026-04-30",
    el_last_desig: "Senior Software Engineer",
    el_dept: "Engineering",
    el_responsibilities: "Led backend development for the payments module; mentored 3 junior engineers; owned deployment pipeline.",
  },

  "termination-letter": {
    tl_company: "Acme Technologies Pvt Ltd",
    tl_letter_date: "2026-05-01",
    tl_signer: "Deepa Menon",
    tl_signer_title: "Head, Human Resources",
    tl_emp_name: "Arjun Patel",
    tl_emp_id: "EMP0127",
    tl_emp_addr: "12/3 Koramangala 7th Block, Bengaluru 560095",
    tl_desig: "Senior Software Engineer",
    tl_reason: "performance",
    tl_reason_details: "As discussed in the performance reviews dated 1 February 2026 and 15 March 2026, and in the Performance Improvement Plan that concluded on 30 April 2026, your performance has not met the required standards.",
    tl_effective: "2026-05-31",
    tl_notice_type: "pay_in_lieu",
    tl_notice_days: "60",
    tl_fnf_amount: "240000",
    tl_handover: "Return laptop (Asset ID L-0127), access cards, and company documents to HR. Complete handover of ongoing projects to Ananya Shah by 31 May 2026.",
  },

  "relieving-letter": {
    rl_company: "Acme Technologies Pvt Ltd",
    rl_letter_date: "2026-05-01",
    rl_signer: "Deepa Menon",
    rl_signer_title: "Head, Human Resources",
    rl_emp_name: "Arjun Patel",
    rl_emp_id: "EMP0127",
    rl_desig: "Senior Software Engineer",
    rl_dept: "Engineering",
    rl_resig_date: "2026-03-01",
    rl_last_working_day: "2026-04-30",
    rl_join_date: "2024-07-01",
  },

  "gift-deed": {
    gd_date: "2026-05-01",
    gd_city: "Bengaluru",
    gd_state: "Karnataka",
    gd_donor_name: "Ramesh Kumar",
    gd_donor_parent: "S/o late Suresh Kumar",
    gd_donor_age: "68",
    gd_donor_addr: "Flat 4B, Lake View Apartments, Indiranagar, Bengaluru 560038",
    gd_donor_pan: "AAAPR1234C",
    gd_donee_name: "Rahul Kumar",
    gd_donee_parent: "S/o Ramesh Kumar",
    gd_donee_age: "38",
    gd_donee_addr: "25 Hosur Road, Bengaluru 560029",
    gd_donee_relation: "Son",
    gd_prop_type: "residential",
    gd_prop_desc: "Flat No. 4B, 2 BHK, 1250 sq ft built-up, Lake View Apartments, Indiranagar, Bengaluru 560038; bounded by - North: Flat 4A; South: Corridor; East: Main Road; West: Parking",
    gd_prop_value: "15000000",
    gd_acquisition: "Purchased vide Sale Deed dated 12 March 2005, registered at SRO Bengaluru East, Reg No. IND-2005-1234",
  },

  "lease-agreement": {
    la_date: "2026-05-01",
    la_city: "Bengaluru",
    la_state: "Karnataka",
    la_term_years: "5",
    la_start: "2026-06-01",
    la_lessor_name: "Ramesh Kumar",
    la_lessor_addr: "Flat 4B, Lake View Apartments, Bengaluru 560038",
    la_lessor_pan: "AAAPR1234C",
    la_lessee_name: "Acme Technologies Pvt Ltd",
    la_lessee_addr: "Plot 42, Whitefield, Bengaluru 560066",
    la_lessee_pan: "AABCA1234M",
    la_prop_use: "commercial",
    la_prop_desc: "Ground floor commercial space, 2500 sq ft carpet area, Unit A-1, Acme Commercial Plaza, 100 Feet Road, Indiranagar, Bengaluru 560038",
    la_area: "2500",
    la_rent: "200000",
    la_escalation_pct: "5",
    la_deposit: "1200000",
    la_lock_in_months: "24",
    la_maint: "25000",
    la_notice_months: "3",
    la_custom: "",
  },
};
